language: node_js
node_js:
  - "7.5"
before_install:
  - npm install npm -g
before_script:
  - npm install -g grunt-cli
script:
  - grunt ci
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
