language: node_js
node_js:
  - "0.10"
before_install:
  - npm install npm@1.4 -g
before_script:
  - npm install -g bower
  - npm install -g grunt-cli
  - bower install
script:
  - grunt ci
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
